### ISSUE TITLE
New version requires XCB 

### ISSUE THREAD

**Issue by rinigus** [ArturGaspar/newcompositor#2]
New version requires XCB which seems to be not available in regular repos. Could you either add required libs into RPM (bundle them under /usr/share/newcompositor/lib) or maybe have a version without this requirement?

**Comment by ArturGaspar** [comment]
It should be installable from my OpenRepos repo, and I've added the build dependencies as well now (libxcb-devel and its requirements). Let me know if there is still interest in a version without the XCB dependency despite this.

**Comment by rinigus** [comment]
I see. Well, it looks like X11 support is important for you. I would have skipped it. But I am not sure it makes sense to have heavy IFDEF sections to get that code out while building newcompositor for Wayland either.

I will be able to get back to chromium building a bit later - want to setup builds for qtwebengine first.

**Comment by ArturGaspar** [comment]
Xwayland support now optional when building with qmake.

**Comment by rinigus** [comment]
Thanks!
